
package com.dgsoft.common.system.wsinterface;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WordDictionaryServiceService", targetNamespace = "http://ws.system.common.dgsoft.com/")
public class WordDictionaryServiceService
    extends Service
{

    public WordDictionaryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WordDictionaryServiceService(String url){
        super(getURL(url), new QName("http://ws.system.common.dgsoft.com/", "WordDictionaryServiceService"));
    }

    private static URL getURL(String url) {

        try {
            return new URL(WordDictionaryServiceService.class.getResource("."), url);
        } catch (MalformedURLException e) {
            throw new IllegalArgumentException(e);
        }

    }

    /**
     * 
     * @return
     *     returns WordDictionaryService
     */
    @WebEndpoint(name = "WordDictionaryServicePort")
    public WordDictionaryService getWordDictionaryServicePort() {
        return super.getPort(new QName("http://ws.system.common.dgsoft.com/", "WordDictionaryServicePort"), WordDictionaryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WordDictionaryService
     */
    @WebEndpoint(name = "WordDictionaryServicePort")
    public WordDictionaryService getWordDictionaryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.system.common.dgsoft.com/", "WordDictionaryServicePort"), WordDictionaryService.class, features);
    }

}
