
package com.dgsoft.common.system.wsinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WordDictionaryService", targetNamespace = "http://ws.system.common.dgsoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WordDictionaryService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDictionary", targetNamespace = "http://ws.system.common.dgsoft.com/", className = "com.dgsoft.system.wsinterface.GetAllDictionary")
    @ResponseWrapper(localName = "getAllDictionaryResponse", targetNamespace = "http://ws.system.common.dgsoft.com/", className = "com.dgsoft.system.wsinterface.GetAllDictionaryResponse")
    public String getAllDictionary();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDictionaryWord", targetNamespace = "http://ws.system.common.dgsoft.com/", className = "com.dgsoft.system.wsinterface.GetDictionaryWord")
    @ResponseWrapper(localName = "getDictionaryWordResponse", targetNamespace = "http://ws.system.common.dgsoft.com/", className = "com.dgsoft.system.wsinterface.GetDictionaryWordResponse")
    public String getDictionaryWord(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDictionaryWords", targetNamespace = "http://ws.system.common.dgsoft.com/", className = "com.dgsoft.system.wsinterface.GetDictionaryWords")
    @ResponseWrapper(localName = "getDictionaryWordsResponse", targetNamespace = "http://ws.system.common.dgsoft.com/", className = "com.dgsoft.system.wsinterface.GetDictionaryWordsResponse")
    public String getDictionaryWords(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDictionaryWordValue", targetNamespace = "http://ws.system.common.dgsoft.com/", className = "com.dgsoft.system.wsinterface.GetDictionaryWordValue")
    @ResponseWrapper(localName = "getDictionaryWordValueResponse", targetNamespace = "http://ws.system.common.dgsoft.com/", className = "com.dgsoft.system.wsinterface.GetDictionaryWordValueResponse")
    public String getDictionaryWordValue(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

}
