package com.dgsoft.house;

/**
 * Created by cooper on 20/11/2016.
 */
public enum  HouseProperty {
    SALE_HOUSE,BACK_HOUSE,PUBLIC_RENT,GOV_RENT,
    LIMIT_PRICE_HOUSE,GOV_SALE_HOUSE,TARGET_HOUSE,
    GROUP_HOUSE,WELFARE_HOUSE,COMM_USE_HOUSE,OTHER,SELF_CREATE;
}
