
package com.dgsoft.developersale.wsinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DeveloperService", targetNamespace = "http://ws.owner.house.dgsoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeveloperService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBuildGridMap", targetNamespace = "http://ws.owner.house.dgsoft.com/", className = "com.dgsoft.developersale.wsinterface.GetBuildGridMap")
    @ResponseWrapper(localName = "getBuildGridMapResponse", targetNamespace = "http://ws.owner.house.dgsoft.com/", className = "com.dgsoft.developersale.wsinterface.GetBuildGridMapResponse")
    public String getBuildGridMap(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPledgeInfo", targetNamespace = "http://ws.owner.house.dgsoft.com/", className = "com.dgsoft.developersale.wsinterface.SearchPledgeInfo")
    @ResponseWrapper(localName = "searchPledgeInfoResponse", targetNamespace = "http://ws.owner.house.dgsoft.com/", className = "com.dgsoft.developersale.wsinterface.SearchPledgeInfoResponse")
    public String searchPledgeInfo(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitContract", targetNamespace = "http://ws.owner.house.dgsoft.com/", className = "com.dgsoft.developersale.wsinterface.SubmitContract")
    @ResponseWrapper(localName = "submitContractResponse", targetNamespace = "http://ws.owner.house.dgsoft.com/", className = "com.dgsoft.developersale.wsinterface.SubmitContractResponse")
    public String submitContract(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logon", targetNamespace = "http://ws.owner.house.dgsoft.com/", className = "com.dgsoft.developersale.wsinterface.Logon")
    @ResponseWrapper(localName = "logonResponse", targetNamespace = "http://ws.owner.house.dgsoft.com/", className = "com.dgsoft.developersale.wsinterface.LogonResponse")
    public String logon(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            String arg2);

}
