
package com.dgsoft.developersale.wsinterface;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebServiceClient(name = "DeveloperServiceService", targetNamespace = "http://ws.owner.house.dgsoft.com/")
public class DeveloperServiceService
        extends Service {


    public DeveloperServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeveloperServiceService(String url) throws MalformedURLException {
        super(getURL(url), new QName("http://ws.owner.house.dgsoft.com/", "DeveloperServiceService"));
    }

    private static URL getURL(String url) throws MalformedURLException {

        return new URL(DeveloperServiceService.class.getResource("."), url);

    }

    /**
     * @return returns DeveloperService
     */
    @WebEndpoint(name = "DeveloperServicePort")
    public DeveloperService getDeveloperServicePort() {
        return super.getPort(new QName("http://ws.owner.house.dgsoft.com/", "DeveloperServicePort"), DeveloperService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DeveloperService
     */
    @WebEndpoint(name = "DeveloperServicePort")
    public DeveloperService getDeveloperServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.owner.house.dgsoft.com/", "DeveloperServicePort"), DeveloperService.class, features);
    }

}
