package cc.coopersoft.house.sale.data;
// Generated Jul 12, 2013 11:32:23 AM by Hibernate Tools 4.0.0

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

/**
 * HouseSellCompany generated by hbm2java
 */
public class HouseSellCompany implements java.io.Serializable {

	private String id;
	private String name;
	private String tel;
	
	
	@JsonProperty("ID")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@JsonProperty("NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@JsonProperty("TEL")
	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}
}
